/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Broker;
import javax.swing.JOptionPane;
import Model.BrokerDirectory;
import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author deepakzedler
 */
public class AddBroker extends javax.swing.JPanel {

    /**
     * Creates new form AddBroker
     */
    int b ;
    BrokerDirectory bd = new BrokerDirectory();
    ArrayList<Broker > blist;
    
  DefaultTableModel model;
    public AddBroker() {
        initComponents();
        

          this.setSize(1024, 768);
        bd=new BrokerDirectory();
        this.b = b;
        //this.blist = bd;
        //String Query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbrokername = new javax.swing.JLabel();
        lbllicenseno = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblbrokerfee = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblmanagement = new javax.swing.JLabel();
        txtbrokername = new javax.swing.JTextField();
        txtlicenseno = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        txtbrokerfee = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtmanagement = new javax.swing.JTextField();
        btnaddbroker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblbrokername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblbrokername.setText("Broker Name:");
        add(lblbrokername);
        lblbrokername.setBounds(270, 70, 82, 18);

        lbllicenseno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lbllicenseno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicenseno.setText("License No:");
        add(lbllicenseno);
        lbllicenseno.setBounds(270, 110, 83, 18);

        lblcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblcontactno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcontactno.setText("Contact No:");
        add(lblcontactno);
        lblcontactno.setBounds(262, 140, 100, 18);

        lblemail.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblemail.setText("Email ID:");
        add(lblemail);
        lblemail.setBounds(270, 180, 83, 18);

        lblbrokerfee.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblbrokerfee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbrokerfee.setText("Broker Fee:");
        add(lblbrokerfee);
        lblbrokerfee.setBounds(270, 230, 83, 18);

        lblusername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setText("Username:");
        lblusername.setFocusTraversalPolicyProvider(true);
        add(lblusername);
        lblusername.setBounds(270, 280, 83, 18);

        lblpassword.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpassword.setText("Password:");
        add(lblpassword);
        lblpassword.setBounds(270, 320, 83, 18);

        lblmanagement.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblmanagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmanagement.setText("Management:");
        add(lblmanagement);
        lblmanagement.setBounds(280, 360, 79, 18);

        txtbrokername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        txtbrokername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrokernameActionPerformed(evt);
            }
        });
        add(txtbrokername);
        txtbrokername.setBounds(380, 60, 145, 24);

        txtlicenseno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtlicenseno);
        txtlicenseno.setBounds(380, 100, 145, 24);

        txtcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtcontactno);
        txtcontactno.setBounds(380, 140, 145, 24);

        txtemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtemailid);
        txtemailid.setBounds(380, 180, 145, 24);

        txtbrokerfee.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtbrokerfee);
        txtbrokerfee.setBounds(380, 230, 145, 24);

        txtusername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtusername);
        txtusername.setBounds(380, 270, 145, 24);

        txtpassword.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtpassword);
        txtpassword.setBounds(380, 310, 145, 24);

        txtmanagement.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtmanagement);
        txtmanagement.setBounds(380, 360, 145, 24);

        btnaddbroker.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnaddbroker.setText("Add Broker");
        btnaddbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbrokerActionPerformed(evt);
            }
        });
        add(btnaddbroker);
        btnaddbroker.setBounds(350, 450, 99, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -30, 1210, 830);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbrokernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrokernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrokernameActionPerformed

    private void btnaddbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbrokerActionPerformed
        // TODO add your handling code here:
        
        String brokername = txtbrokername.getText();
        String Licenseno = txtlicenseno.getText();
        String contact = txtcontactno.getText();
        String email = txtemailid.getText();
        String brokerfee = txtbrokerfee.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String management = txtmanagement.getText();
        
        if(brokername.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Broker Name");
        }else if(Licenseno.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the License Number");
        }else if(contact.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Contact Number");
        }else if(email.isBlank()){
               JOptionPane.showMessageDialog(this,"Please enter the Email ID");
        }else if(brokerfee.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Broker Fee");
        }else if(username.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Username");
        }else if(password.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Password");
        }else if(management.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Management");
        }else{
            //JOptionPane.showMessageDialog(this,"Registeration Successfull");
        
        System.out.println("Before try statement executed");
       
       try {
    System.out.println("Inside try statement executed");

    // Establishing the database connection
    Connection con = SQLconnection.dbconnector();
    Statement stmt = con.createStatement();

    // Corrected SQL query with column names in the exact order of the table structure
    String Query = "INSERT INTO Brokers (LicenseNumber, Name, ContactNumber, BrokerFee, Management, EmailID, Username, Password) " +
                   "VALUES ('" + txtlicenseno.getText() + "', '" + txtbrokername.getText() + "', '" + txtcontactno.getText() + "', " +
                   "'" + txtbrokerfee.getText() + "', '" + txtmanagement.getText() + "', '" + txtemailid.getText() + "', " +
                   "'" + txtusername.getText() + "', '" + txtpassword.getText() + "')";
    
    // Executing the query
    stmt.executeUpdate(Query);

    // Closing the statement and connection
    stmt.close();
    con.close();

    // Success message
    JOptionPane.showMessageDialog(this, "Registered Successfully");
} catch (SQLException e) {
    // Handling SQL exceptions
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error occurred while adding broker: " + e.getMessage());
}
        
}
    }//GEN-LAST:event_btnaddbrokerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbroker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbrokerfee;
    private javax.swing.JLabel lblbrokername;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lbllicenseno;
    private javax.swing.JLabel lblmanagement;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtbrokerfee;
    private javax.swing.JTextField txtbrokername;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtlicenseno;
    private javax.swing.JTextField txtmanagement;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
