/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Broker;
import javax.swing.JOptionPane;
import Model.BrokerDirectory;
import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author deepakzedler
 */
public class AddBroker extends javax.swing.JPanel {

    /**
     * Creates new form AddBroker
     */
    int b ;
    BrokerDirectory bd = new BrokerDirectory();
    ArrayList<Broker > blist;
    
  DefaultTableModel model;
    public AddBroker() {
        initComponents();
        

          this.setSize(1024, 768);
        bd=new BrokerDirectory();
        this.b = b;
        //this.blist = bd;
        //String Query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbrokername = new javax.swing.JLabel();
        lbllicenseno = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblbrokerfee = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblmanagement = new javax.swing.JLabel();
        txtbrokername = new javax.swing.JTextField();
        txtlicenseno = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        txtbrokerfee = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtmanagement = new javax.swing.JTextField();
        btnaddbroker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblbrokername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokername.setText("Broker Name:");
        add(lblbrokername);
        lblbrokername.setBounds(330, 60, 83, 15);

        lbllicenseno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllicenseno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbllicenseno.setText("License No:");
        add(lbllicenseno);
        lbllicenseno.setBounds(330, 100, 83, 15);

        lblcontactno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontactno.setText("Contact No:");
        add(lblcontactno);
        lblcontactno.setBounds(350, 130, 72, 15);

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemail.setText("Email ID:");
        add(lblemail);
        lblemail.setBounds(330, 170, 83, 15);

        lblbrokerfee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokerfee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblbrokerfee.setText("Broker Fee:");
        add(lblbrokerfee);
        lblbrokerfee.setBounds(330, 210, 83, 15);

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusername.setText("Username:");
        lblusername.setFocusTraversalPolicyProvider(true);
        add(lblusername);
        lblusername.setBounds(330, 260, 83, 15);

        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpassword.setText("Password:");
        add(lblpassword);
        lblpassword.setBounds(330, 300, 83, 15);

        lblmanagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmanagement.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmanagement.setText("Management:");
        add(lblmanagement);
        lblmanagement.setBounds(330, 340, 83, 15);

        txtbrokername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrokernameActionPerformed(evt);
            }
        });
        add(txtbrokername);
        txtbrokername.setBounds(440, 50, 145, 23);
        add(txtlicenseno);
        txtlicenseno.setBounds(440, 90, 145, 23);
        add(txtcontactno);
        txtcontactno.setBounds(440, 130, 145, 23);
        add(txtemailid);
        txtemailid.setBounds(440, 170, 145, 23);
        add(txtbrokerfee);
        txtbrokerfee.setBounds(440, 210, 145, 23);
        add(txtusername);
        txtusername.setBounds(440, 250, 145, 23);
        add(txtpassword);
        txtpassword.setBounds(440, 290, 145, 23);
        add(txtmanagement);
        txtmanagement.setBounds(440, 330, 145, 23);

        btnaddbroker.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnaddbroker.setText("Add Broker");
        btnaddbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbrokerActionPerformed(evt);
            }
        });
        add(btnaddbroker);
        btnaddbroker.setBounds(440, 440, 100, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -30, 1210, 830);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbrokernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrokernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrokernameActionPerformed

    private void btnaddbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbrokerActionPerformed
        // TODO add your handling code here:
        
        String brokername = txtbrokername.getText();
        String Licenseno = txtlicenseno.getText();
        String contact = txtcontactno.getText();
        String email = txtemailid.getText();
        String brokerfee = txtbrokerfee.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String management = txtmanagement.getText();
        
        if(brokername.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Broker Name");
        }else if(Licenseno.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the License Number");
        }else if(contact.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Contact Number");
        }else if(email.isBlank()){
               JOptionPane.showMessageDialog(this,"Please enter the Email ID");
        }else if(brokerfee.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Broker Fee");
        }else if(username.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Username");
        }else if(password.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Password");
        }else if(management.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Management");
        }else{
            //JOptionPane.showMessageDialog(this,"Registeration Successfull");
        
        System.out.println("Before try statement executed");
       
        try {
            System.out.println("Inside try statement executed");
              Connection con=SQLconnection.dbconnector();
            Statement stmt=con.createStatement();
            
          String Query= "INSERT INTO Brokers(name,licenseno,contactno,emailid,brokerfee,USERNAME,PASSWORD,management) values('"+txtbrokername.getText()+"','"+txtlicenseno.getText()+"','"+txtcontactno.getText()+"','"+txtemailid.getText()+"','"+txtbrokerfee.getText()+"','"+txtusername.getText()+"','"+txtpassword.getText()+"','"+txtmanagement.getText()+"')";
          
         
            stmt.executeUpdate(Query);
          stmt.close();
          con.close();
            JOptionPane.showMessageDialog(this, "Registered Sucessfully");
       
            
        
       
        } catch (SQLException ex) {
            Logger.getLogger(AddBroker.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    }//GEN-LAST:event_btnaddbrokerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbroker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbrokerfee;
    private javax.swing.JLabel lblbrokername;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lbllicenseno;
    private javax.swing.JLabel lblmanagement;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtbrokerfee;
    private javax.swing.JTextField txtbrokername;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtlicenseno;
    private javax.swing.JTextField txtmanagement;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
