/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.SQLconnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author deepakzedler
 */
public class AddstudentsPage extends javax.swing.JPanel {

    /**
     * Creates new form AddstudentsPage
     */
    public AddstudentsPage() {
        initComponents();
        this.setSize(1024, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        lblemailid = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        btnaddstudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        setLayout(null);

        lblid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblid.setText("ID:");
        add(lblid);
        lblid.setBounds(320, 150, 25, 15);

        lblname.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name:");
        add(lblname);
        lblname.setBounds(300, 200, 46, 15);

        lblcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblcontactno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontactno.setText("Contact No:");
        add(lblcontactno);
        lblcontactno.setBounds(270, 240, 75, 15);

        lblemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblemailid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemailid.setText("Email ID:");
        add(lblemailid);
        lblemailid.setBounds(290, 300, 59, 15);

        lblusername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusername.setText("Username:");
        add(lblusername);
        lblusername.setBounds(280, 340, 65, 15);

        txtid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtid);
        txtid.setBounds(390, 150, 151, 23);

        txtname.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname);
        txtname.setBounds(390, 190, 151, 23);

        txtcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtcontactno);
        txtcontactno.setBounds(390, 240, 151, 23);

        txtemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtemailid);
        txtemailid.setBounds(390, 290, 151, 23);

        txtusername.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtusername);
        txtusername.setBounds(390, 340, 151, 23);

        lblpassword.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpassword.setText("Password:");
        add(lblpassword);
        lblpassword.setBounds(280, 400, 72, 15);

        txtpassword.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        add(txtpassword);
        txtpassword.setBounds(390, 390, 151, 23);

        btnaddstudent.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnaddstudent.setText("Add Student");
        btnaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstudentActionPerformed(evt);
            }
        });
        add(btnaddstudent);
        btnaddstudent.setBounds(360, 460, 124, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -30, 930, 820);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstudentActionPerformed
       // TODO add your handling code here:
         String name = txtname.getText();
        String id= txtid.getText();
        String contactno = txtcontactno.getText();
        String emailid = txtemailid.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        if(name.isBlank() ){
            JOptionPane.showMessageDialog(this,"Please enter the Name");
        }else if(id.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the ID");
        }else if(contactno.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Contact Number");
        }else if(emailid.isBlank()){
               JOptionPane.showMessageDialog(this,"Please enter the Email ID");
        }else if(username.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Username");
        }else if(password.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Password");
        }else{
            //JOptionPane.showMessageDialog(this,"Registeration Successfull");
        
            System.out.println("Before try statement executed");
       
            try {
                System.out.println("Inside try statement executed");
                Connection con=SQLconnection.dbconnector();
                Statement stmt=con.createStatement();
                
                // Updated Query to match the Student table column names
                String Query= "INSERT INTO student (ID, Name, ContactNo, EmailID, Username, Password) VALUES ('"
                        + txtid.getText() + "', '"
                        + txtname.getText() + "', '"
                        + txtcontactno.getText() + "', '"
                        + txtemailid.getText() + "', '"
                        + txtusername.getText() + "', '"
                        + txtpassword.getText() + "')";
                
                stmt.executeUpdate(Query);
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(this, "Registered Successfully");
            } catch (SQLException ex) {
                Logger.getLogger(AddstudentsPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnaddstudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lblemailid;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
