/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Apartmentlistings;
import Model.Broker;
import Model.Market;
import Model.Requeststudent;
import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Model.Markethistory;
import Model.Market;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author deepakzedler
 */
public class MarketplaceAddproducts extends javax.swing.JPanel {

    /**
     * Creates new form MarketplaceAddproducts
     */
   
    
    Markethistory mh= new Markethistory();
    Market mp;
    public MarketplaceAddproducts() {
        initComponents();
        mh.getMarketHistory();
        this.mp = mp;
        PopulateTable();
           
          
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmarketplace = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 153, 153));
        setFocusTraversalPolicyProvider(true);
        setName(""); // NOI18N

        tblmarketplace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Used / Unused", "Image"
            }
        ));
        jScrollPane1.setViewportView(tblmarketplace);

        btndelete.setText("REMOVE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btndelete)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       // Handle product deletion using prepopulated data
    int selectedRowIndex = tblmarketplace.getSelectedRow();

    try {
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid row to delete!");
            return;
        }

        // Access the table model
        DefaultTableModel model = (DefaultTableModel) tblmarketplace.getModel();

        // Fetch the selected market object using the row index
        Market mp = mh.getList().get(selectedRowIndex);

        // Remove the selected market object from the list
        mh.deleteMarket(mp);

        // Refresh the table after deletion
        PopulateTable();

        // Notify the user about successful deletion
        JOptionPane.showMessageDialog(this, "Deleted Successfully!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An error occurred while deleting the row: " + ex.getMessage());
    }
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmarketplace;
    // End of variables declaration//GEN-END:variables
private void PopulateTable() {
    DefaultTableModel model = (DefaultTableModel) tblmarketplace.getModel();
    model.setRowCount(0); // Clear existing rows in the table

    // Iterate through the prepopulated market list and add rows to the table
    for (Market mp : mh.getList()) {
        Object[] row = new Object[4]; // Adjusted to match the table columns
        row[0] = mp.getName();       // Product Name
        row[1] = mp.getPrice();      // Price
        row[2] = mp.getUsed();       // Used/Unused Status
        row[3] = mp.getImage();      // Image Path (optional visibility)

        model.addRow(row); // Add the row to the table model
    }
}
}
