/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author deepakzedler
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        this.setResizable(false); //This is the Start page. Main

          this.setSize(1024, 768); // Set to your desired fixed size

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnstudent = new javax.swing.JButton();
        btnuniversity = new javax.swing.JButton();
        btnheadrealtor = new javax.swing.JButton();
        btnbroker = new javax.swing.JButton();
        btnlandlord = new javax.swing.JButton();
        btnmarketplaceadmin = new javax.swing.JButton();
        btntechsupport = new javax.swing.JButton();
        btnsysadmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("AppleMyungjo", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HuskyHomestead");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 1040, 50);

        btnstudent.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnstudent.setText("Student ");
        btnstudent.setBorder(null);
        btnstudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnstudent);
        btnstudent.setBounds(430, 120, 150, 30);

        btnuniversity.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnuniversity.setText("University Admin");
        btnuniversity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnuniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuniversityActionPerformed(evt);
            }
        });
        jPanel1.add(btnuniversity);
        btnuniversity.setBounds(430, 170, 150, 24);

        btnheadrealtor.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnheadrealtor.setText("Head Realtor");
        btnheadrealtor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnheadrealtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnheadrealtorActionPerformed(evt);
            }
        });
        jPanel1.add(btnheadrealtor);
        btnheadrealtor.setBounds(430, 220, 150, 24);

        btnbroker.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnbroker.setText("Broker");
        btnbroker.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrokerActionPerformed(evt);
            }
        });
        jPanel1.add(btnbroker);
        btnbroker.setBounds(430, 270, 150, 24);

        btnlandlord.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnlandlord.setText("Landlord");
        btnlandlord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlandlordActionPerformed(evt);
            }
        });
        jPanel1.add(btnlandlord);
        btnlandlord.setBounds(430, 320, 150, 24);

        btnmarketplaceadmin.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnmarketplaceadmin.setText("Marketplace Admin");
        btnmarketplaceadmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmarketplaceadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarketplaceadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnmarketplaceadmin);
        btnmarketplaceadmin.setBounds(430, 370, 144, 24);

        btntechsupport.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btntechsupport.setText("Tech Support");
        btntechsupport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntechsupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntechsupportActionPerformed(evt);
            }
        });
        jPanel1.add(btntechsupport);
        btntechsupport.setBounds(430, 420, 150, 24);

        btnsysadmin.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnsysadmin.setText("System Admin");
        btnsysadmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsysadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsysadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnsysadmin);
        btnsysadmin.setBounds(430, 470, 150, 24);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/StartPage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-420, -10, 1560, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsysadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsysadminActionPerformed
        // TODO add your handling code here:
         SystemadminLoginpage frame=new SystemadminLoginpage();
                frame.setTitle("System Admin");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
        
    }//GEN-LAST:event_btnsysadminActionPerformed

    private void btnuniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuniversityActionPerformed
        // TODO add your handling code here:
       UniversityadminLoginpage frame=new UniversityadminLoginpage();
                frame.setTitle("University");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnuniversityActionPerformed

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed
        // TODO add your handling code here:
        LogonPage frame=new LogonPage();
                frame.setTitle("Student");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnstudentActionPerformed

    private void btnheadrealtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnheadrealtorActionPerformed
        // TODO add your handling code here:
         HeadRealtorLoginpage frame=new HeadRealtorLoginpage();
                frame.setTitle("Head Realtor");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnheadrealtorActionPerformed

    private void btnbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrokerActionPerformed
        // TODO add your handling code here:
        BrokerLoginpage frame=new BrokerLoginpage();
                frame.setTitle("Broker");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnbrokerActionPerformed

    private void btnlandlordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlandlordActionPerformed
        // TODO add your handling code here:
         LandlordLoginpage frame=new LandlordLoginpage();
                frame.setTitle("Landlord");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnlandlordActionPerformed

    private void btnmarketplaceadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarketplaceadminActionPerformed
        // TODO add your handling code here:
         MarketplaceadminLoginpage frame=new MarketplaceadminLoginpage ();
                frame.setTitle("Market Place");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnmarketplaceadminActionPerformed

    private void btntechsupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntechsupportActionPerformed
        // TODO add your handling code here:
        TechsupportLoginpage frame=new TechsupportLoginpage ();
                frame.setTitle("Technical Support");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btntechsupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbroker;
    private javax.swing.JButton btnheadrealtor;
    private javax.swing.JButton btnlandlord;
    private javax.swing.JButton btnmarketplaceadmin;
    private javax.swing.JButton btnstudent;
    private javax.swing.JButton btnsysadmin;
    private javax.swing.JButton btntechsupport;
    private javax.swing.JButton btnuniversity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
