/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author snegahshree
 */
public class StudentDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetailsPage
     */
    public StudentDetailsPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        lblemailid = new javax.swing.JLabel();
        btnrequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 170, 151, -1));

        txtname.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 216, 151, -1));

        txtcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 264, 151, -1));

        txtemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 315, 151, -1));

        lblid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblid.setText("ID:");
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 174, 25, -1));

        lblname.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name:");
        jPanel1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 46, -1));

        lblcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblcontactno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontactno.setText("Contact No:");
        jPanel1.add(lblcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 268, 75, -1));

        lblemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        lblemailid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemailid.setText("Email ID:");
        jPanel1.add(lblemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 319, 59, -1));

        btnrequest.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnrequest.setText("Request");
        btnrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestActionPerformed(evt);
            }
        });
        jPanel1.add(btnrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestActionPerformed
        // TODO add your handling code here:
        // Validate all fields
    if (txtid.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter ID.");
        return;
    }
    if (txtname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Name.");
        return;
    }
    if (txtcontactno.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Contact Number.");
        return;
    }
    if (txtemailid.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Email ID.");
        return;
    }

    try {
        // Establish connection
        Connection con = SQLconnection.dbconnector();

        // Prepare SQL insert statement
        PreparedStatement stmt = con.prepareStatement(
            "INSERT INTO BookingRequest (Name, ID, EmailId, ContactNo) VALUES (?, ?, ?, ?)"
        );
        stmt.setString(1, txtname.getText());
        stmt.setInt(2, Integer.parseInt(txtid.getText())); // Parse ID as integer
        stmt.setString(3, txtemailid.getText());
        stmt.setString(4, txtcontactno.getText());

        stmt.executeUpdate(); // Execute the insert query
        stmt.close(); // Close the statement
        con.close(); // Close the connection

        JOptionPane.showMessageDialog(this, "Request sent successfully!");
        this.setVisible(false); // Close the current frame
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please ensure ID is a valid number.");
        ex.printStackTrace();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error sending request: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnrequestActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lblemailid;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
