/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Broker;
import Model.BrokerDirectory;
import Model.Student;
import Model.StudentDirectory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import UI.ViewBrokers;
import java.awt.CardLayout;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sneghashree
 */

  
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form StudentView
     */

  
    public StudentView() {
        initComponents();
        this.setSize(1024, 768);
        getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        setTitle("Student Housing");
    
      
  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        btnbrokers = new javax.swing.JButton();
        btnapartment = new javax.swing.JButton();
        btnroommate = new javax.swing.JButton();
        btnreportissue = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbrokers.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnbrokers.setText("View Brokers");
        btnbrokers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrokersActionPerformed(evt);
            }
        });
        jPanel3.add(btnbrokers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 178, -1));

        btnapartment.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnapartment.setText("Apartment Listings");
        btnapartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapartmentActionPerformed(evt);
            }
        });
        jPanel3.add(btnapartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 188, -1));

        btnroommate.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnroommate.setText("Products for Sale");
        btnroommate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroommateActionPerformed(evt);
            }
        });
        jPanel3.add(btnroommate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 188, -1));

        btnreportissue.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnreportissue.setText("Report an Issue");
        btnreportissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportissueActionPerformed(evt);
            }
        });
        jPanel3.add(btnreportissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 188, -1));

        btnlogout.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 641, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 750));

        SplitPane.setLeftComponent(jPanel3);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 770);

        SplitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbrokersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrokersActionPerformed
        
        ViewBrokers viewbrokers = new ViewBrokers();
        SplitPane.setRightComponent(viewbrokers);
     
       
    }//GEN-LAST:event_btnbrokersActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnreportissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportissueActionPerformed
        // TODO add your handling code here:
        ViewReportedissues viewreportissue = new ViewReportedissues();
        
        SplitPane.setRightComponent(viewreportissue);
    }//GEN-LAST:event_btnreportissueActionPerformed

    private void btnapartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapartmentActionPerformed
        // TODO add your handling code here:
         ViewApartmentlistings viewapartmentlistings = new ViewApartmentlistings();
        SplitPane.setRightComponent(viewapartmentlistings);
        
    }//GEN-LAST:event_btnapartmentActionPerformed

    private void btnroommateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroommateActionPerformed
        // TODO add your handling code here:
        
        ViewProducts vp = new ViewProducts();
        SplitPane.setRightComponent(vp);
    }//GEN-LAST:event_btnroommateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
            
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnapartment;
    private javax.swing.JButton btnbrokers;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreportissue;
    private javax.swing.JButton btnroommate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
