/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.BrokerDirectory;
import Model.Broker;
import Model.SQLconnection;
import Model.Student;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author deepakzedler
 */

public class ViewBrokers extends javax.swing.JPanel {

    /**
     * Creates new form ViewBrokers
     */
    BrokerDirectory bd = new BrokerDirectory();
    ArrayList<Broker> blist;
    DefaultTableModel model;
  
    public ViewBrokers() {
        initComponents();
        this.setSize(1024, 768);
        bd.getBrokerDirectory();
        

        PopulateTable();
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbrokers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbbrokerfee = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtlicenseno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcontactno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbrokerfee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmanagement = new javax.swing.JTextField();
        btnbook = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jRadioButton1.setText("jRadioButton1");

        jLabel2.setText("jLabel2");

        jLabel11.setText("jLabel11");

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblbrokers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblbrokers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "License Number", "Name", "Contact Number", "Broker Fee", "Management", "Email ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbrokers.setShowHorizontalLines(true);
        tblbrokers.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblbrokers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 180));

        jLabel1.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Broker Fee :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 92, -1));

        cmbbrokerfee.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        cmbbrokerfee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1000", "2000", "3000", "4000", "5000" }));
        cmbbrokerfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbrokerfeeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbbrokerfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 168, -1));

        btnsearch.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, 30));

        btnrefresh.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 160, 30));

        jLabel3.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("License Number : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 101, -1));

        txtlicenseno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtlicenseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 168, -1));

        jLabel5.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 49, -1));

        txtname.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 168, -1));

        jLabel6.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Contact Number : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 113, -1));

        txtcontactno.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 168, -1));

        jLabel7.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Broker Fee :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 420, 80, -1));

        txtbrokerfee.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtbrokerfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 168, -1));

        jLabel8.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Management :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 120, -1));

        txtmanagement.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtmanagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 168, -1));

        btnbook.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnbook.setText("Book Appointment");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        jPanel1.add(btnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 200, 60));

        btnview.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 160, 30));

        jLabel10.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email id :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 65, -1));

        txtemailid.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jPanel1.add(txtemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 168, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 760));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:

        
       int selectedRowIndex = tblbrokers.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Select a row to view details.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblbrokers.getModel();

        // Populate text fields with the selected row's data
        txtlicenseno.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtcontactno.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtbrokerfee.setText(model.getValueAt(selectedRowIndex, 3).toString());
        txtmanagement.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txtemailid.setText(model.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
       
      
               StudentDetailsPage frame = new StudentDetailsPage();
         frame.setTitle("Student Details Page");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
            
            
        

    }//GEN-LAST:event_btnbookActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:

        // Clear fields
        txtlicenseno.setText("");
        txtname.setText("");
        txtcontactno.setText("");
        txtbrokerfee.setText("");
        txtmanagement.setText("");
        txtemailid.setText("");

        // Repopulate table
        PopulateTable();

    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
       String query = cmbbrokerfee.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tblbrokers.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblbrokers.setRowSorter(trs);

        if (!query.equals("Select")) {
            trs.setRowFilter(RowFilter.regexFilter(query));
        } else {
            tblbrokers.setRowSorter(trs); // Reset sorting
        }
    
    }//GEN-LAST:event_btnsearchActionPerformed

    private void cmbbrokerfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbrokerfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbrokerfeeActionPerformed
  
   
  
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbook;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> cmbbrokerfee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable tblbrokers;
    private javax.swing.JTextField txtbrokerfee;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtlicenseno;
    private javax.swing.JTextField txtmanagement;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
 private void PopulateTable()
    {
        // Clear existing rows
        DefaultTableModel model = (DefaultTableModel) tblbrokers.getModel();
        model.setRowCount(0);

        try {
            Connection con = SQLconnection.dbconnector(); // Establish connection
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM Brokers"); // Query for fetching broker data
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[6]; // Match the column count in your table
                row[0] = rs.getInt("LicenseNumber");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("ContactNumber");
                row[3] = rs.getInt("BrokerFee");
                row[4] = rs.getString("Management");
                row[5] = rs.getString("EmailID");

                model.addRow(row); // Add row to table
            }
            stmt.close();
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching broker data: " + ex.getMessage());
        }
    }
 public void search(String str,int i) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    System.out.println(str);
        DefaultTableModel model = (DefaultTableModel) tblbrokers.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblbrokers.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str,i));
        
    }

}
