 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.ApartmentHistory;
import Model.Requestapartment;
import Model.Requeststudent;
import Model.Studenthistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sneghashree
 */
public class ViewHousetourbookings extends javax.swing.JPanel {

    /**
     * Creates new form ViewHousetourbookings
     */
     Studenthistory history = new Studenthistory();
     ApartmentHistory hist = new ApartmentHistory();
    public ViewHousetourbookings() {
        initComponents();
        this.setSize(1024, 768);
       history.getStudentHistory();
       hist.getApartmentHistory();
        PopulateTable();
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblviewstudent = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblviewapartment = new javax.swing.JTable();
        btnrequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblviewstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Contact Number", "Email ID", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblviewstudent);
        if (tblviewstudent.getColumnModel().getColumnCount() > 0) {
            tblviewstudent.getColumnModel().getColumn(4).setMinWidth(0);
            tblviewstudent.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblviewstudent.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 660, 140));

        tblviewapartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Apartment Name", "Apartment type", "Price ", "Landlord Name", "Apartment ID", "null"
            }
        ));
        jScrollPane2.setViewportView(tblviewapartment);
        if (tblviewapartment.getColumnModel().getColumnCount() > 0) {
            tblviewapartment.getColumnModel().getColumn(5).setMinWidth(0);
            tblviewapartment.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblviewapartment.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 658, 129));

        btnrequest.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnrequest.setText("Request Landlord");
        btnrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestActionPerformed(evt);
            }
        });
        add(btnrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 145, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void btnrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblviewstudent.getSelectedRow();
        
       DefaultTableModel model= (DefaultTableModel) tblviewstudent.getModel();
        model.setRowCount(0);
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this,"Please select a row ");
        }
        else{
            model.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblviewapartment;
    private javax.swing.JTable tblviewstudent;
    // End of variables declaration//GEN-END:variables
 private void PopulateTable() {
        
        DefaultTableModel model= (DefaultTableModel) tblviewstudent.getModel();
        model.setRowCount(0);
        
        for (Requeststudent s : history.getHistory()){
        
        Object[] row = new Object[5];
            row[0] = s.getId();
            row[1] = s.getName();
            row[2] = s.getContactNumber();
            row[3] = s.getEmailId();
            row[4] = s;
           
            model.addRow(row);
        }
        
        }
 private void populateTable(){
       
        DefaultTableModel model= (DefaultTableModel) tblviewapartment.getModel();
        model.setRowCount(0);
        
        for (Requestapartment a : hist.getApartmentHistory()){
        
        Object[] row = new Object[6];
            row[0] = a.getApartmentName();
            row[1] = a.getApartmentType();
            row[2] = a.getPrice();
            row[3] = a.getLandlordName();
            row[4] = a.getApartmentID();
            row[5]=a;
           
            model.addRow(row);
     
        }
 }
 }
