/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author sneghashree
 */
public class ViewProductsforsale extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductsforsale
     */
    public ViewProductsforsale() {
        initComponents();
        this.setSize(1024, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtissue = new javax.swing.JTextArea();
        cmbissue = new javax.swing.JComboBox<>();
        btnreport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 154, 154));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtissue.setColumns(20);
        txtissue.setRows(5);
        jScrollPane1.setViewportView(txtissue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 382, 206));

        cmbissue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Payment ", "Appointment Booking ", "Login Issue", " ", " " }));
        add(cmbissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnreport.setText("Report");
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });
        add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnreportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreport;
    private javax.swing.JComboBox<String> cmbissue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtissue;
    // End of variables declaration//GEN-END:variables
}
