/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nsarv
 */
public class ViewReportedissues extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportedissues
     */
    public ViewReportedissues() {
        initComponents();
        this.setSize(1024, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        rbtnresolved = new javax.swing.JRadioButton();
        rbtnpending = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsolution = new javax.swing.JTextArea();
        lblsuggest = new javax.swing.JLabel();
        lblstudentemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnemail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup.add(rbtnresolved);
        rbtnresolved.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnresolved.setText("Issue Resolved");
        rbtnresolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnresolvedActionPerformed(evt);
            }
        });
        add(rbtnresolved, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        buttonGroup.add(rbtnpending);
        rbtnpending.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnpending.setText("Issue Pending");
        rbtnpending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnpendingActionPerformed(evt);
            }
        });
        add(rbtnpending, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        txtsolution.setColumns(20);
        txtsolution.setRows(5);
        jScrollPane1.setViewportView(txtsolution);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 377, 172));

        lblsuggest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsuggest.setText("Suggest a Solution:");
        add(lblsuggest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        lblstudentemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblstudentemail.setText("Student Email ID:");
        add(lblstudentemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 258, -1));

        btnemail.setText("Send ");
        btnemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemailActionPerformed(evt);
            }
        });
        add(btnemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Images/gradient (1).jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnpendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnpendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnpendingActionPerformed

    private void rbtnresolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnresolvedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnresolvedActionPerformed

    private void btnemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemailActionPerformed
        // TODO add your handling code here:
      //String report = buttonGroup.getSelection().toString();
       ButtonModel m = null;
        if(buttonGroup.isSelected(m)){
            JOptionPane.showMessageDialog(this, "Please select an Option");
        }else if(txtsolution.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please describe the Solution");
        }else if(txtemail.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter mail Id");
        }else if(rbtnresolved.isSelected()){
        
        
        
       String ToEmail = txtemail.getText();
        String FromEmail = "aedproject123@gmail.com";//studyviral2@gmail.com
        String FromEmailPassword = "wiiwhakaddhmcypq";//You email Password from you want to send email
       String Subjects = "Resolved";
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        properties.put("mail.smtp.starttls.required", "true");
properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
properties.put("mail.debug", "true");
        
       
           
        
       Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(FromEmail, FromEmailPassword);
            }
     
        });
       try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
      
            message.setText(txtsolution.getText()+"\n" +"Thank you for contacting us! ");
            Transport.send(message);
            
                JOptionPane.showMessageDialog(this, "Issue successfully resolved");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        
        }else if(rbtnpending.isSelected()){
              String ToEmail = txtemail.getText();
        String FromEmail = "aedproject123@gmail.com";//studyviral2@gmail.com
        String FromEmailPassword = "wiiwhakaddhmcypq";//You email Password from you want to send email
        String Subjects = "Pending";
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true");
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.put("mail.smtp.port","587");
        properties.put("mail.smtp.starttls.required", "true");
properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
properties.put("mail.debug", "true");
        
       
           
        
       Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(FromEmail, FromEmailPassword);
            }
     
        });
       try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
      
            message.setText(txtsolution.getText()+"\n" +"Thank you for contacting us! ");
            Transport.send(message);
            
                JOptionPane.showMessageDialog(this, "Issue Pending");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
               
               
    
        }

       
        
        


        
        
    }//GEN-LAST:event_btnemailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnemail;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblstudentemail;
    private javax.swing.JLabel lblsuggest;
    private javax.swing.JRadioButton rbtnpending;
    private javax.swing.JRadioButton rbtnresolved;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextArea txtsolution;
    // End of variables declaration//GEN-END:variables
}
